# Generated by Django 5.2 on 2025-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='api_author_name',
            field=models.CharField(default='', help_text="Exact author name format for API search (e.g., 'Yann LeCun')", max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeacherPaper',
        ),
    ]
